### ISSUE TITLE
Initial State Machine

### ISSUE THREAD

**Issue by drhuffman12** [drhuffman12/smcr#4]
- [x] Initial repo setup (#1)
- [x] Initial code using `Symbol`'s (#2)
- [x] Switch to `Enum`'s (#3)
- [x] Add code re Edit Paths (#5)
- [ ] Add code re Attempt State Change (and handle if state_change fails due to invalid attempt) (#6)
- [ ] Add code re Callbacks (and handle what state should we fail over to if Callbacks fails) (#6)
  - [ ] Add abstract logic for callbacks
  - [ ] Add 'real' logic for callbacks in a test
- [ ] Add 'How to use' documentation
- [ ] _Version bump along the way_
